openapi: 3.1.0
info:
  title: user-manager
  description: ''
  contact:
    name: FLECS Technologies GmbH
  license:
    name: Apache-2.0
    identifier: Apache-2.0
  version: 0.2.1
paths:
  /clients:
    get:
      tags:
      - rest::clients
      operationId: get
      responses:
        '200':
          description: List of all clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientSummary'
    put:
      tags:
      - rest::clients
      operationId: put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClient'
        required: true
      responses:
        '201':
          description: Client was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClientResponse'
        '400':
          description: Invalid request body
          content:
            text/plain:
              schema:
                type: string
        '403':
          description: Caller does not have all requested groups
          content:
            text/plain:
              schema:
                type: string
        '409':
          description: Client with that name already exists
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /clients/{cid}:
    get:
      tags:
      - rest::clients::cid
      operationId: get
      parameters:
      - name: cid
        in: path
        description: Client UUID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Return a single client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientSummary'
        '400':
          description: Invalid client ID
        '404':
          description: Client does not exist
    delete:
      tags:
      - rest::clients::cid
      operationId: delete
      parameters:
      - name: cid
        in: path
        description: Client UUID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Client was deleted
        '400':
          description: Invalid client ID
        '403':
          description: Client is read-only
        '404':
          description: Client does not exist
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /meta/issuer:
    get:
      tags:
      - Experimental
      operationId: get
      responses:
        '200':
          description: Issuer that issues auth tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Uri'
  /meta/jwk:
    get:
      tags:
      - Experimental
      operationId: get
      responses:
        '200':
          description: Jwk that has to be used to verify issued tokens
          content:
            application/json:
              schema: {}
  /users:
    get:
      tags:
      - rest::users
      operationId: get
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserSummary'
    post:
      tags:
      - rest::users
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        '201':
          description: User was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/u16'
        '400':
          description: Invalid request body
          content:
            text/plain:
              schema:
                type: string
        '409':
          description: User with that name already exists
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /users/self:
    delete:
      tags:
      - rest::users::self_
      operationId: delete
      responses:
        '204':
          description: User was deleted
        '401':
          description: Not authenticated
        '403':
          description: Cannot delete the super admin
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
    patch:
      tags:
      - rest::users::self_
      operationId: patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
        required: true
      responses:
        '204':
          description: User was updated
        '400':
          description: Invalid request body
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Not authenticated
        '409':
          description: User with that name already exists
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /users/super-admin:
    get:
      tags:
      - Experimental
      operationId: get
      responses:
        '204':
          description: Super admin exists
        '404':
          description: Super admin does not exist
    post:
      tags:
      - Experimental
      operationId: post
      requestBody:
        description: The super admin that should be set
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuperAdmin'
        required: true
      responses:
        '200':
          description: Super admin was created
        '400':
          description: Invalid password
          content:
            text/plain:
              schema:
                type: string
        '409':
          description: Super admin already exists
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /users/{uid}:
    get:
      tags:
      - rest::users::uid
      operationId: get
      parameters:
      - name: uid
        in: path
        description: User ID to query
        required: true
        schema:
          $ref: '#/components/schemas/u16'
      responses:
        '200':
          description: Return a single user by its uid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSummary'
        '400':
          description: Invalid user ID
        '404':
          description: User does not exist
    delete:
      tags:
      - rest::users::uid
      operationId: delete
      parameters:
      - name: uid
        in: path
        description: User ID to delete
        required: true
        schema:
          $ref: '#/components/schemas/u16'
      responses:
        '204':
          description: User was deleted
        '400':
          description: Invalid user ID
        '403':
          description: Cannot delete the super admin
        '404':
          description: User does not exist
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
    patch:
      tags:
      - rest::users::uid
      operationId: patch
      parameters:
      - name: uid
        in: path
        description: User ID to update
        required: true
        schema:
          $ref: '#/components/schemas/u16'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
        required: true
      responses:
        '204':
          description: User was updated
        '400':
          description: Invalid request body or user ID
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: User does not exist
        '409':
          description: User with that name already exists
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /users/{uid}/roles:
    get:
      tags:
      - rest::users::uid::roles
      operationId: get
      parameters:
      - name: uid
        in: path
        description: User ID to query roles for
        required: true
        schema:
          $ref: '#/components/schemas/u16'
      responses:
        '200':
          description: List of roles assigned to the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupId'
                uniqueItems: true
        '400':
          description: Invalid user ID
        '404':
          description: User does not exist
    put:
      tags:
      - rest::users::uid::roles
      operationId: put
      parameters:
      - name: uid
        in: path
        description: User ID to assign roles to
        required: true
        schema:
          $ref: '#/components/schemas/u16'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/GroupId'
              uniqueItems: true
        required: true
      responses:
        '204':
          description: Roles were assigned to the user
        '400':
          description: Invalid request body or user ID
        '404':
          description: User does not exist
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
  /users/{uid}/roles/{role}:
    put:
      tags:
      - rest::users::uid::roles::role
      operationId: put
      parameters:
      - name: uid
        in: path
        description: User ID to assign the role to
        required: true
        schema:
          $ref: '#/components/schemas/u16'
      - name: role
        in: path
        description: Role to assign
        required: true
        schema:
          $ref: '#/components/schemas/GroupId'
      responses:
        '204':
          description: Role was assigned to the user
        '400':
          description: Invalid user ID or role
        '404':
          description: User does not exist
        '409':
          description: User already has this role
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
    delete:
      tags:
      - rest::users::uid::roles::role
      operationId: delete
      parameters:
      - name: uid
        in: path
        description: User ID to remove the role from
        required: true
        schema:
          $ref: '#/components/schemas/u16'
      - name: role
        in: path
        description: Role to remove
        required: true
        schema:
          $ref: '#/components/schemas/GroupId'
      responses:
        '204':
          description: Role was removed from the user
        '400':
          description: Invalid user ID or role
        '404':
          description: User does not exist or does not have this role
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    ClientSummary:
      type: object
      required:
      - id
      - name
      - auth_method
      - groups
      - created_at
      properties:
        auth_method:
          type: string
        created_at:
          type: string
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupId'
          uniqueItems: true
        id:
          type: string
        name:
          type: string
    CreateAuthMethod:
      oneOf:
      - type: object
        required:
        - type
        properties:
          type:
            type: string
            enum:
            - Secret
      - type: object
        required:
        - type
        properties:
          pem:
            type:
            - string
            - 'null'
          type:
            type: string
            enum:
            - Certificate
    CreateClient:
      type: object
      required:
      - name
      - auth_method
      - groups
      properties:
        auth_method:
          $ref: '#/components/schemas/CreateAuthMethod'
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupId'
          uniqueItems: true
        name:
          type: string
    CreateClientResponse:
      type: object
      required:
      - id
      - name
      - auth_method
      - groups
      - created_at
      properties:
        auth_method:
          type: string
        certificate:
          type:
          - string
          - 'null'
        created_at:
          type: string
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupId'
          uniqueItems: true
        id:
          type: string
        name:
          type: string
        private_key:
          type:
          - string
          - 'null'
        secret:
          type:
          - string
          - 'null'
    CreateUser:
      type: object
      required:
      - name
      - password
      - groups
      properties:
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupId'
          uniqueItems: true
        name:
          type: string
        password:
          type: string
    GroupId:
      type: string
    SuperAdmin:
      type: object
      required:
      - name
      - full_name
      - password
      properties:
        full_name:
          type: string
        name:
          type: string
        password:
          type: string
    UpdateUser:
      type: object
      properties:
        full_name:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        password:
          type:
          - string
          - 'null'
    Uri:
      type: string
      format: uri
    UserSummary:
      type: object
      required:
      - id
      - name
      - groups
      properties:
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupId'
          uniqueItems: true
        id:
          $ref: '#/components/schemas/u16'
        name:
          type: string
    u16:
      type: integer
      format: int32
      minimum: 0
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
